# Generated by Django 5.1.2 on 2024-10-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='sanitised_name',
            field=models.CharField(default='Amenity Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
