# Generated by Django 5.1.2 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_amenities_sanitised_name_alter_amenities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icon',
            field=models.CharField(default='Font Awesome Icon', max_length=150),
        ),
    ]
