# Generated by Django 5.1.2 on 2024-10-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_amenities_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
