# Generated by Django 5.1.2 on 2024-12-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
